version: '3.9'

services:
  db:
    image: postgres:14.7-alpine
    container_name: db
    env_file:
      - .env.docker
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: app
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
    command: >
     bash -c "python manage.py migrate
     && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .env.docker:/app/habit/.env


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data

  celery:
    build: .
    container_name: celery
    command: bash -c "celery -A config.celery:app worker --beat --loglevel=info"
    volumes:
      - .:/app/habit
      - .env.docker:/app/habit/.env
    links:
      - redis
    depends_on:
      - db
      - app

volumes:
  pgdata:
  redis_data:
